## **Wine Dataset**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
data = pd.read_csv('/content/Wine.csv')
data.head()

1  14.23  1.71  2.43  15.6  127  ...   .28  2.29  5.64  1.04  3.92  1065
0  1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
1  1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
2  1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
3  1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735
4  1  14.20  1.76  2.45  15.2  112  ...  0.34  1.97  6.75  1.05  2.85  1450

[5 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df, train_df['1065'], test_df['1065'] = train_test_split(data.drop(['1065'], axis=1), data['1065'], test_size=0.2, random_state=42, shuffle=True)
train_df.head()

1  14.23  1.71  2.43  15.6  127  ...   .28  2.29   5.64  1.04  3.92  1065
156  3  12.45  3.03  2.64  27.0   97  ...  0.63  1.14   7.50  0.67  1.73   880
136  3  12.53  5.51  2.64  25.0   96  ...  0.63  1.10   5.00  0.82  1.69   515
98   2  12.29  3.17  2.21  18.0   88  ...  0.45  2.81   2.30  1.42  2.83   406
158  3  13.48  1.67  2.64  22.5   89  ...  0.52  2.29  11.75  0.57  1.78   620
38   1  14.22  3.99  2.51  13.2  128  ...  0.20  2.08   5.10  0.89  3.53   760

[5 rows x 14 columns]

In [ ]:
predictors = train_df.columns[:-1]
target = '1065'

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_train = scaler.fit_transform(train_df)
scaled_train

array([[1.        , 0.30409357, 0.45256917, ..., 0.14285714, 0.16849817,
        0.42938659],
       [1.        , 0.32748538, 0.94268775, ..., 0.30769231, 0.15384615,
        0.16904422],
       [0.5       , 0.25730994, 0.48023715, ..., 0.96703297, 0.57142857,
        0.09129815],
       ...,
       [0.        , 0.64912281, 0.21146245, ..., 0.81318681, 0.58974359,
        0.7360913 ],
       [0.5       , 0.25730994, 0.41304348, ..., 0.67032967, 0.74358974,
        0.0085592 ],
       [0.5       , 0.11988304, 0.19367589, ..., 0.43956044, 0.42857143,
        0.09771755]])

In [ ]:
scaled_train_df = pd.DataFrame(scaled_train, columns=train_df.columns.values)
scaled_train_df

1     14.23      1.71      2.43  ...      5.64      1.04      3.92      1065
0    1.0  0.304094  0.452569  0.684492  ...  0.511545  0.142857  0.168498  0.429387
1    1.0  0.327485  0.942688  0.684492  ...  0.289520  0.307692  0.153846  0.169044
2    0.5  0.257310  0.480237  0.454545  ...  0.049734  0.967033  0.571429  0.091298
3    1.0  0.605263  0.183794  0.684492  ...  0.888988  0.032967  0.186813  0.243937
4    0.0  0.821637  0.642292  0.614973  ...  0.298401  0.384615  0.827839  0.343795
..   ...       ...       ...       ...  ...       ...       ...       ...       ...
136  0.5  0.608187  0.181818  0.470588  ...  0.177620  0.483516  0.553114  0.138374
137  0.5  0.383041  0.199605  0.491979  ...  0.138544  0.373626  0.421245  0.149786
138  0.0  0.649123  0.211462  0.716578  ...  0.493783  0.813187  0.589744  0.736091
139  0.5  0.257310  0.413043  0.459893  ...  0.036412  0.670330  0.743590  0.008559
140  0.5  0.119883  0.193676  0.278075  ...  0.028419  0.439560  0.428571  0.097718

[141 rows x 14 columns]

### **Model Building**

In [ ]:
# Sequential Layer
model = Sequential()

In [ ]:
# Hidden layers
model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=50, activation='relu'))

In [ ]:
# Output Layer
model.add(Dense(1))

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
X = scaled_train_df.drop(target, axis=1).values
y = scaled_train_df[[target]].values

In [ ]:
# Train the model

model.fit(
    x=X,
    y=y,
    epochs=100,
    shuffle=True,
    verbose=2,
)

Epoch 1/100
5/5 - 1s - loss: 0.1472
Epoch 2/100
5/5 - 0s - loss: 0.0642
Epoch 3/100
5/5 - 0s - loss: 0.0545
Epoch 4/100
5/5 - 0s - loss: 0.0359
Epoch 5/100
5/5 - 0s - loss: 0.0311
Epoch 6/100
5/5 - 0s - loss: 0.0238
Epoch 7/100
5/5 - 0s - loss: 0.0201
Epoch 8/100
5/5 - 0s - loss: 0.0174
Epoch 9/100
5/5 - 0s - loss: 0.0156
Epoch 10/100
5/5 - 0s - loss: 0.0140
Epoch 11/100
5/5 - 0s - loss: 0.0131
Epoch 12/100
5/5 - 0s - loss: 0.0121
Epoch 13/100
5/5 - 0s - loss: 0.0116
Epoch 14/100
5/5 - 0s - loss: 0.0112
Epoch 15/100
5/5 - 0s - loss: 0.0109
Epoch 16/100
5/5 - 0s - loss: 0.0105
Epoch 17/100
5/5 - 0s - loss: 0.0105
Epoch 18/100
5/5 - 0s - loss: 0.0100
Epoch 19/100
5/5 - 0s - loss: 0.0099
Epoch 20/100
5/5 - 0s - loss: 0.0098
Epoch 21/100
5/5 - 0s - loss: 0.0093
Epoch 22/100
5/5 - 0s - loss: 0.0092
Epoch 23/100
5/5 - 0s - loss: 0.0091
Epoch 24/100
5/5 - 0s - loss: 0.0089
Epoch 25/100
5/5 - 0s - loss: 0.0087
Epoch 26/100
5/5 - 0s - loss: 0.0086
Epoch 27/100
5/5 - 0s - loss: 0.0085
Epoch 28/1

In [ ]:
def scaler_inverse_transform(value):
    scaled_prediction = value
    scaled_prediction -= added_factor
    return scaled_prediction / multiply_factor

In [ ]:
multiply_factor = scaler.scale_[13]
added_factor = scaler.min_[13]

In [ ]:
scaler_inverse_transform(y[:1][0][0])

880.0000000000001

In [ ]:
prediction = model.predict(X[:])
prediction

array([[0.36570427],
       [0.28068492],
       [0.07873827],
       [0.27831736],
       [0.40484995],
       [0.23603286],
       [0.14409848],
       [0.30712387],
       [0.2361295 ],
       [0.7387372 ],
       [0.17364688],
       [0.12364849],
       [0.33638492],
       [0.7455412 ],
       [0.20642725],
       [0.7364393 ],
       [0.61929965],
       [0.33556908],
       [0.20974231],
       [0.08403543],
       [0.12399986],
       [0.58863115],
       [0.11266497],
       [0.5029471 ],
       [0.13465881],
       [0.2290644 ],
       [0.3175808 ],
       [0.3376878 ],
       [0.7466683 ],
       [0.7133562 ],
       [0.62844783],
       [0.34674257],
       [0.801901  ],
       [0.67628324],
       [0.26937127],
       [0.27626923],
       [0.16184269],
       [0.7273968 ],
       [0.26546898],
       [0.12790506],
       [0.5722055 ],
       [0.28288046],
       [0.05367552],
       [0.23931494],
       [0.65968794],
       [0.08394552],
       [0.5441963 ],
       [0.562

In [ ]:
for idx in range(141):    
    print(f"Actual Price: {scaler_inverse_transform(y[idx][0])* 1000:.2f}$")
    print(f"Predicted Price: {scaler_inverse_transform(prediction[idx][0])* 1000:.2f}$")
    print("-"*30)

Actual Price: 880000.00$
Predicted Price: 790717.38$
------------------------------
Actual Price: 515000.00$
Predicted Price: 671520.26$
------------------------------
Actual Price: 406000.00$
Predicted Price: 388391.06$
------------------------------
Actual Price: 620000.00$
Predicted Price: 668200.94$
------------------------------
Actual Price: 760000.00$
Predicted Price: 845599.62$
------------------------------
Actual Price: 680000.00$
Predicted Price: 608918.07$
------------------------------
Actual Price: 495000.00$
Predicted Price: 480026.06$
------------------------------
Actual Price: 718000.00$
Predicted Price: 708587.67$
------------------------------
Actual Price: 550000.00$
Predicted Price: 609053.57$
------------------------------
Actual Price: 1480000.00$
Predicted Price: 1313709.59$
------------------------------
Actual Price: 562000.00$
Predicted Price: 521452.93$
------------------------------
Actual Price: 380000.00$
Predicted Price: 451355.19$
---------------------

## **Diabetes Dataset**

In [ ]:
data = pd.read_csv('/content/pima-indians-diabetes.csv')
data.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
train_df, test_df, train_df['1'], test_df['1'] = train_test_split(data.drop(['1'], axis=1), data['1'], test_size=0.2, random_state=42, shuffle=True)
train_df.head()

6  148  72  35    0  33.6  0.627  50  1
60   8  133  72   0    0  32.9  0.270  39  1
554  7  124  70  33  215  25.5  0.161  37  0
346  3  116   0   0    0  23.5  0.187  23  0
294  6  151  62  31  120  35.5  0.692  28  0
231  1   79  80  25   37  25.4  0.583  22  0

In [ ]:
predictors = train_df.columns[:-1]
target = '1'

In [ ]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_train = scaler.fit_transform(train_df)
scaled_train

array([[0.47058824, 0.67171717, 0.59016393, ..., 0.08198121, 0.3       ,
        1.        ],
       [0.41176471, 0.62626263, 0.57377049, ..., 0.0354398 , 0.26666667,
        0.        ],
       [0.17647059, 0.58585859, 0.        , ..., 0.04654142, 0.03333333,
        0.        ],
       ...,
       [0.11764706, 0.54545455, 0.50819672, ..., 0.02134927, 0.        ,
        0.        ],
       [0.70588235, 0.70707071, 0.69672131, ..., 0.07087959, 0.33333333,
        0.        ],
       [0.05882353, 0.40909091, 0.59016393, ..., 0.08753202, 0.05      ,
        0.        ]])

In [ ]:
scaled_train_df = pd.DataFrame(scaled_train, columns=train_df.columns.values)
scaled_train_df

6       148        72        35  ...      33.6     0.627        50    1
0    0.470588  0.671717  0.590164  0.000000  ...  0.490313  0.081981  0.300000  1.0
1    0.411765  0.626263  0.573770  0.523810  ...  0.380030  0.035440  0.266667  0.0
2    0.176471  0.585859  0.000000  0.000000  ...  0.350224  0.046541  0.033333  0.0
3    0.352941  0.762626  0.508197  0.492063  ...  0.529061  0.262169  0.116667  0.0
4    0.058824  0.398990  0.655738  0.396825  ...  0.378539  0.215628  0.016667  0.0
..        ...       ...       ...       ...  ...       ...       ...       ...  ...
608  0.764706  0.636364  0.737705  0.000000  ...  0.646796  0.215628  0.350000  1.0
609  0.235294  0.727273  0.475410  0.444444  ...  0.439642  0.089240  0.266667  0.0
610  0.117647  0.545455  0.508197  0.507937  ...  0.375559  0.021349  0.000000  0.0
611  0.705882  0.707071  0.696721  0.523810  ...  0.557377  0.070880  0.333333  0.0
612  0.058824  0.409091  0.590164  0.285714  ...  0.396423  0.087532  0.050000  0.0

[613 rows x 9 columns]

### **Model Building**

In [ ]:
# Sequential Layer
model = Sequential()

In [ ]:
# Hidden layers
model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=50, activation='relu'))

In [ ]:
# Output Layer
model.add(Dense(1))

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
X = scaled_train_df.drop(target, axis=1).values
y = scaled_train_df[[target]].values

In [ ]:
# Train the model

model.fit(
    x=X,
    y=y,
    epochs=100,
    shuffle=True,
    verbose=2,
)

Epoch 1/100
20/20 - 0s - loss: 0.2263
Epoch 2/100
20/20 - 0s - loss: 0.1931
Epoch 3/100
20/20 - 0s - loss: 0.1850
Epoch 4/100
20/20 - 0s - loss: 0.1771
Epoch 5/100
20/20 - 0s - loss: 0.1718
Epoch 6/100
20/20 - 0s - loss: 0.1668
Epoch 7/100
20/20 - 0s - loss: 0.1633
Epoch 8/100
20/20 - 0s - loss: 0.1596
Epoch 9/100
20/20 - 0s - loss: 0.1577
Epoch 10/100
20/20 - 0s - loss: 0.1550
Epoch 11/100
20/20 - 0s - loss: 0.1555
Epoch 12/100
20/20 - 0s - loss: 0.1509
Epoch 13/100
20/20 - 0s - loss: 0.1504
Epoch 14/100
20/20 - 0s - loss: 0.1461
Epoch 15/100
20/20 - 0s - loss: 0.1453
Epoch 16/100
20/20 - 0s - loss: 0.1439
Epoch 17/100
20/20 - 0s - loss: 0.1433
Epoch 18/100
20/20 - 0s - loss: 0.1421
Epoch 19/100
20/20 - 0s - loss: 0.1434
Epoch 20/100
20/20 - 0s - loss: 0.1441
Epoch 21/100
20/20 - 0s - loss: 0.1356
Epoch 22/100
20/20 - 0s - loss: 0.1475
Epoch 23/100
20/20 - 0s - loss: 0.1374
Epoch 24/100
20/20 - 0s - loss: 0.1343
Epoch 25/100
20/20 - 0s - loss: 0.1375
Epoch 26/100
20/20 - 0s - loss: 0.

In [ ]:
def scaler_inverse_transform(value):
    scaled_prediction = value
    scaled_prediction -= added_factor
    return scaled_prediction / multiply_factor

In [ ]:
multiply_factor = scaler.scale_[8]
added_factor = scaler.min_[8]

In [ ]:
scaler_inverse_transform(y[:1][0][0])

1.0

In [ ]:
prediction = model.predict(X[:])
prediction

array([[ 6.17406011e-01],
       [ 3.19043666e-01],
       [ 4.06908572e-01],
       [ 6.39888585e-01],
       [ 7.76783973e-02],
       [ 3.88929397e-01],
       [ 9.84085858e-01],
       [ 5.32869026e-02],
       [ 3.37145269e-01],
       [ 4.24175978e-01],
       [ 6.60856962e-01],
       [ 1.10798943e+00],
       [ 1.17372799e+00],
       [ 4.47167277e-01],
       [ 1.05994725e+00],
       [ 8.78430367e-01],
       [ 1.25124955e+00],
       [ 5.07582366e-01],
       [ 6.85405076e-01],
       [ 1.87631205e-01],
       [ 7.44486094e-01],
       [ 2.70933025e-02],
       [ 1.15799144e-01],
       [ 6.41443357e-02],
       [ 4.20104504e-01],
       [ 4.73719060e-01],
       [ 4.04845268e-01],
       [ 8.03582221e-02],
       [ 5.27745306e-01],
       [ 1.81049243e-01],
       [ 8.02635372e-01],
       [ 1.25856817e-01],
       [ 3.30491006e-01],
       [ 6.00565672e-02],
       [ 3.62231851e-01],
       [ 8.90142769e-02],
       [-9.50824656e-03],
       [ 6.12867117e-01],
       [ 4.7

In [ ]:
for idx in range(613):    
    print(f"Actual Price: {scaler_inverse_transform(y[idx][0])* 1000:.2f}$")
    print(f"Predicted Price: {scaler_inverse_transform(prediction[idx][0])* 1000:.2f}$")
    print("-"*30)

Actual Price: 1000.00$
Predicted Price: 617.41$
------------------------------
Actual Price: 0.00$
Predicted Price: 319.04$
------------------------------
Actual Price: 0.00$
Predicted Price: 406.91$
------------------------------
Actual Price: 0.00$
Predicted Price: 639.89$
------------------------------
Actual Price: 0.00$
Predicted Price: 77.68$
------------------------------
Actual Price: 0.00$
Predicted Price: 388.93$
------------------------------
Actual Price: 1000.00$
Predicted Price: 984.09$
------------------------------
Actual Price: 0.00$
Predicted Price: 53.29$
------------------------------
Actual Price: 0.00$
Predicted Price: 337.15$
------------------------------
Actual Price: 0.00$
Predicted Price: 424.18$
------------------------------
Actual Price: 0.00$
Predicted Price: 660.86$
------------------------------
Actual Price: 1000.00$
Predicted Price: 1107.99$
------------------------------
Actual Price: 1000.00$
Predicted Price: 1173.73$
------------------------------
